### ISSUE TITLE
Copy/pastable inspect protocol for tags

### ISSUE THREAD

**Issue by zachallaun** [fuelen/owl#12]
Latest versions of Elixir have moved to a copy-pastable Inspect convention. E.g. from MapSet:

```
iex> MapSet.new([1, :two, {"three"}])
MapSet.new([1, :two, {"three"}])
```

Tags could do the same:

```
iex> Owl.Data.tag(“hello”, :red)
Owl.Data.tag(“hello”, :red)
```

Happy to implement. :)

**Comment by fuelen** [comment]
@zachallaun I think I can prepare a new release v0.7.0
Do you have other ideas you'd like to implement for the release? :)

**Comment by zachallaun** [comment]
I think I’m all set for now! The next thing drawing my attention is figuring out some kind of raw terminal mode, but that’s obviously a much larger task :P

**Comment by fuelen** [comment]
Released! :tada:
