### ISSUE TITLE
Flapping display when spinners scroll off-screen

### ISSUE THREAD

**Issue by adamwight** [fuelen/owl#17]
I'm running a concurrent job and each thread has its own progress spinner.  What I've found is that the spinners display correctly as long as they're all in the visible terminal area, but once they scroll off-screen then the spinners begin to compete with one another for updates.  Instead of updating in-place, each spinner is repeatedly written at the bottom of output as a new line.

Here's a minimal example (terminal must be < 100 rows tall):
```elixir
1..100
|> Enum.each(fn x ->
  Task.async(fn ->
    Owl.Spinner.run(
      fn ->
        Process.sleep(5_000)
        :ok
      end,
      labels: [
        ok: "Completed: #{x}",
        processing: "Processing: #{x}",
      ]
    )
  end)
end)

Process.sleep(5_000)
```

Thank you for the great library!

**Comment by fuelen** [comment]
Thanks for the report.
I think this is not even possible to fix :confused:

**Comment by adamwight** [comment]
In my case, if I could define a "block" which held all of the spinners (so perhaps a hierarchy of blocks containing smaller blocks), then we could simply not render the ones which would be off-screen?

**Comment by adamwight** [comment]
I think the feature I was looking for is more of an ncurses thing.  Your suggestion in #18 helped me find a totally different solution.

Maybe it's worth mentioning this limitation in the docs, that the number of live blocks shouldn't exceed the terminal height?  The condition could possibly be detected with `:io.rows()` but I'm not sure what the correct reponse would be.
