### ISSUE TITLE
Owl.LiveScreen issues on Elixir >= 1.15 ?

### ISSUE THREAD

**Issue by johnknott** [fuelen/owl#23]
I tried the compiler example with both Terminal.app and ITerm2 and it just intermingles the content, but the same code works perfectly on Linux - keeping the outputs separate. Other examples all seem to work fine. Is this expected?
![Screenshot 2024-03-15 at 10 30 46](https://github.com/fuelen/owl/assets/201271/d478e815-ef89-44dd-9daa-1eea7b3796a0)

**Comment by fuelen** [comment]
No, this is not an expected behaviour.
Unfortunately, I can't test on macOS.

Which OTP and Elixir versions do you use?

**Comment by johnknott** [comment]
Some progress - I've done some further investigation and found the bug exists for me on both Mac and Linux, but only on Elixir versions >= 1.15.

I found an easy way to test was with Docker, and mount the 'compile.ex' example as a volume. I installed latest version of Owl with Mix.install at the top of compile.ex. It's not Owl version related as I've tested lots of versions and they all behave similarly.

`docker run -it  -v ./compile.ex:/compile.ex elixir:1.14.5-otp-25-alpine elixir compile.ex` - works well.

`docker run -it  -v ./compile.ex:/compile.ex elixir:1.15.7-otp-25-alpine elixir compile.ex` - exhibits the intermingling bug.

Elixir 1.16.x also had the same issues.

When it comes to OTP versions, I found the latest version of OTP (26.2.3) segfaulted on both Linux and Mac, not sure why that happens though so I stuck with OTP 25.

Hope this helps.

**Comment by johnknott** [comment]
My latest thinking is this is caused by the big changes to the Logger in Elixir 1.15, where it was change to be backed by Erlang's :logger - but that is as far as I have got.

**Comment by fuelen** [comment]
I've pushed updates to examples, so they are compatible with Elixir >=1.15.

If you want to use backends, then drop this line to `config/config.exs`:
```elixir
config :logger, :backends, [Logger.Backends.Console]
```
and replace this line in code
```elixir
Logger.configure_backend(:console, device: Owl.LiveScreen)
```
with
```elixir
Logger.configure_backend(Logger.Backends.Console, device: Owl.LiveScreen)
```
