### ISSUE TITLE
`Owl.Box` collapses newlines

### ISSUE THREAD

**Issue by zachallaun** [fuelen/owl#6]
Hi there! First off, thanks very much for making such a useful library. I've been working on a library with a CLI and Owl has been a really big improvement.

I noticed what I assume is a bug in `Owl.Box` where consecutive newlines are collapsed to a single newline. I admit that I haven't done further testing to know whether this is actually an issue with some other primitive that `Owl.Box` is using, or whether it's specific to the box implementation.

```elixir
iex(1)> "foo\nbar" |> Owl.Box.new() |> Owl.IO.puts()
┌───┐
│foo│
│bar│
└───┘
:ok

iex(2)> "foo\n\nbar" |> Owl.Box.new() |> Owl.IO.puts()
┌───┐
│foo│
│bar│
└───┘
:ok

iex(3)> "foo\n\n\nbar" |> Owl.Box.new() |> Owl.IO.puts()
┌───┐
│foo│
│bar│
└───┘
:ok

iex(4)> "foo\n \n\nbar" |> Owl.Box.new() |> Owl.IO.puts()
┌───┐
│foo│
│   │
│bar│
└───┘
:ok
```

Adding additional newline characters does not affect the formatting, unless a space is added (as on `iex(4)`), in which case the line with the space will be respected.

This makes it somewhat difficult to insert preformatted text. If you are inserting a single preformatted string, you can get around this by splitting on newlines, mapping over the result and replacing every `""` with `" "` before re-joining on newlines, but this is bit of non-obvious extra work. =)

**Comment by fuelen** [comment]
Hi @zachallaun 

Thank you for the report. Pushed a fix
