### ISSUE TITLE
Proposal: Add `Owl.Data.from_ansidata/1` - mechanism for dealing with existing escape codes

### ISSUE THREAD

**Issue by zachallaun** [fuelen/owl#9]
### Context

One of the really awesome things that `owl` brings to the table is the notion of tags. They're a great primitive that dramatically simplify a lot of things.

An issue I've run up against, however, is that some things break down when you are dealing with iodata that already include ANSI escape sequences. For instance, formatting and syntax-highlighting code using `Inspect.Algebra.to_doc/2` and `Inspect.Algebra.format/2` does not provide a mechanism other than applying the escape sequences from `IO.ANSI`. When this iodata is then used with things like `Owl.Box` or `Owl.Table`, things break because length calculations for each line assume that data is formatted using tags.

The first time I ran into this, I was able to [submit a PR](https://github.com/hrzndhrn/rewrite/pull/14) to the library that allowed me to use `Owl.Data.tag/2` to colorize, but I think it's pretty well outside the scope of Elixir core to expect a similar option there. 🙂 

### Proposal

Add `Owl.Data.from_ansidata/1` to convert existing formatted iodata to `Owl.Data.t()`.

I would personally be fine with the constraint that the iodata should be "well formatted" in that escape sequences should be separate binaries in a list, not concatenated strings. For example:

```elixir
iex> ansidata = IO.ANSI.format([:red, "foo"])
[[[[] | "\e[31m"], "foo"], | "\e[0m"]

iex> Owl.Data.from_ansidata(ansidata)
[#Owl.Tag[:red]<"foo">]

iex> Owl.Data.from_ansidata("\e[31mfoo\e[0m")
["\e[31mfoo\e[0m"]
```

**Comment by zachallaun** [comment]
As with #10, I'd be happy to contribute this.

**Comment by zachallaun** [comment]
Would it be convenient when working on this to simultaneously add the other sequences supported by `IO.ANSI` that aren’t yet in `Owl.Data` — for instance, the `:font_1, :font_2, etc.` variants. Any objections to that?

**Comment by fuelen** [comment]
No objections. Which terminal do you use that supports `:font_*`? :)

**Comment by zachallaun** [comment]
I don’t! Though I’ve been wanting to try WezTerm, which I believe does. :) I was more thinking about it for completeness’ sake. Not something I feel strongly about, but was browsing through ANSI.IO looking at all the sequences defined and thought about it.

**Comment by fuelen** [comment]
Are we ready to close the issue?
